### ISSUE TITLE
Date and time are not working

### ISSUE THREAD

**Issue by aditi1421** [Nirmal-Data-Scientist/Twitter_Scraping#2]
Hi!
The date and time for username/keyword/hashtag does not work, do you know why? 
Example - I put a date range from 21st May - 31st May under the option username and it still shows me the output as tweets for only 28 May.

**Comment by nirmals-workspace** [comment]
Hello Aditi! Sorry for the oversight and thanks for bringing it to my attention.... I have resolved it now I guess.... Please check it out and inform me if you face any further issues.... Also, one more thing to mention here is, snscrape will fetch you only up to the previous day's tweets.... So keep that in mind while scraping and also as you asked for in your previous issue, I have put in some checks to ensure API limit....

I will keep this issue open and will close it once you ensure that there are no more errors in my app.... Leaving the app badge below....

[![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://nirmal-data-scientist-twitter-data-fetching.streamlit.app/)


Thanks and Regards,
Nirmal

**Comment by aditi1421** [comment]
Yup, works for me for now, great project.
Thanks!

**Comment by nirmals-workspace** [comment]
Great to hear that.... Thanks, from my part as well Aditi!
