### ISSUE TITLE
snscrape not working

### ISSUE THREAD

**Issue by ihabpalamino** [Nirmal-Data-Scientist/Twitter_Scraping#6]
hello actually using snscrape gives the error blocked 404 so this library is it still working?do u any idea about any update about this error?

**Comment by nirmals-workspace** [comment]
Hello @ihabpalamino. There's an ongoing rate limit issue with twitter and it would obviously cause the 404 error... So, as of now  none of the library would work in scraping tweets as far as I know

**Comment by ihabpalamino** [comment]
i hope a solution would be found soon it been 2 weeks that i am waiting for it !!!!!

**Comment by nirmals-workspace** [comment]
You might have to use twitter API.... Otherwise, I don't think twitter is going to lift this restriction anytime soon....

**Comment by ihabpalamino** [comment]
thank you my firend if is it possible since i've never worked with twitter api could u provide me an example of code python using twitter api that scraps tweet content and there ids,number of likes shares and comment and url by username and the since until date please my freind help me and thanks

**Comment by nirmals-workspace** [comment]
Even I haven't tried my hands with twitter API @ihabpalamino ... Sorry for that....

**Comment by ihabpalamino** [comment]
i have seen that you did some updates in your project does it work again??

**Comment by nirmals-workspace** [comment]
No buddy, it's related to something else.... I have no time to experiment it as of now.... May be after a month or so, I would find some time.... Let's see...
